### ISSUE TITLE
Config option to boot nodes using UEFI

### ISSUE THREAD

**Issue by richang2009** [ubccr/grendel#36]
Hi, 
I am not able a to boot servers Servers set to EFI boot. Is there any config example I can use?
Thanks.

**Comment by aebruno** [comment]
@amnesium Can you provide some more details on the type of hardware, bios, architecture, etc?

**Comment by jafurlan** [comment]
@amnesium Can you try setting the firmware to use `snponly-x86_64.efi`? I believe currently we default to legacy boot and manually override for UEFI, this should probably be reversed.

`grendel node edit <nodename>`
`"firmware": "snponly-x86_64.efi",`

This also needs to be documented, apologies for the lack thereof.

**Comment by aebruno** [comment]
Fixed in #82

**Comment by amnesium** [comment]
Hi @aebruno, thanks for the answer and updating the doc.
Unfortunately, even forcing the firmware to "snponly-x86_64.efi" or even "ipxe-x86_64.efi", I'm still not able to boot in UEFI mode.
I tried with multiple server brands, including Gigabyte and Supermicro and with both version 0.1.0 and 0.2.0 of grendel.

Here is my image.json:
```
[{
    "name": "rocky9",
    "kernel": "rocky9/vmlinuz-5.14.0-503.35.1.el9_5.x86_64",
    "initrd": [
        "rocky9/initramfs-live-5.14.0-503.35.1.el9_5.x86_64.img"
    ],
    "cmdline": "rd.live.overlay.readonly=1 rd.live.overlay.overlayfs=1 root=live:http://192.168.8.8/repo/rocky9/rocky9.5-compute-baremetal-amd64.squashfs BOOTIF={{ $.nic.MAC }} rd.neednet=1 ip=dhcp"
}]
```
And the host.json
```
[{
    "name": "labhost",
    "provision": true,
    "boot_image": "rocky9",
    "firmware": "snponly-x86_64.efi",
    "interfaces": [
        {
            "fqdn": "rocky9.localdomain",
            "ip": "192.168.8.10/24",
            "mac": "AC:1F:6B:02:79:DA",
            "bmc": false
        }
    ]
}]
```
Looking at the logs, the `Bootfile Name` seems malformed or incomplete. 
Any idea?

[grendel-0.1.0-rocky9-uefi.log](https://github.com/user-attachments/files/19863377/grendel-0.1.0-rocky9-uefi.log)
[grendel-0.2.0-rocky9-uefi.log](https://github.com/user-attachments/files/19863376/grendel-0.2.0-rocky9-uefi.log)
